apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-quota-dev
  namespace: dev
  labels:
    app: myapp
    type: front-end
spec:
  hard:
    pods: "2"
    requests.cpu: "4"
    requests.memory: 1Gi
    limits.cpu: "10"
    limits.memory: 2Gi