apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  namespace: prod
  labels:
    app: myapp
    type: front-end
spec:
  containers:
    - name: nginx-container
      image: nginx
      envFrom:
        - configMapRef:
            # matches name in config map metadata
            name: myapp-config